server:
  port: 8086
spring:
  application:
    name: study-mobile
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
  datasource:
    url: jdbc:mysql://47.94.169.13:3306/linjiashop?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 111111
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 47.94.169.13 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: 123456 # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 5000 # 连接超时时间（毫秒）
  mail:
    port: 587
    username: 1136081721@qq.com
    password: yjl19890519
    protocol: smtp
    default-encoding: UTF-8
    host: smtp.qq.com
    properties:
      smtp:
        auth: true
        ssl:
          enable: true
  cache:
    ehcache:
      config: ehcache.xml
  main:
    allow-bean-definition-overriding: true
  http:
    converters:
      preferred-json-mapper: jackson
jwt:
  user:
    type: 0